### ISSUE TITLE
Improved support for inherited classes

### ISSUE THREAD

**Issue by ekutner** [otsaloma/attd#3]
The __coerce() method is using self.__class__ to make sure assignments are of the correct class (usually AttrDict). This works well when using the class by itself, but sometimes it is useful to inherit it in order to add some specific functionality. In those scenarios self.__class__ points to the inheriting class, however it is not always desirable that the children will be of the type of the inheriting class and then it would be better to instantiate the children explicitly as AttrDict. One such example is when the inheriting class doesn't have the default dict constructor, so this call fails: return self.__class__(value).
It will be very useful if this could be controlled with a parameter that the inheriting class could pass to AttrDict when calling its constructor. I would argue that it's better for the default behavior to be that children are instantiated as AttrDict but that would break the current behavior so it could be reversed.

Does that make sense?

**Comment by otsaloma** [comment]
It's easy to think of counter-examples why the current way makes more sense. For example, if someone wants to add YAML from/to methods similar to JSON, they'd do

```python
class MyAttributeDict(AttributeDict):

    @classmethod
    def from_yaml(cls, string, **kwargs):
        ...

    def to_yaml(self, **kwargs):
        ...
```

and everything would work right, including dumping sub-dictionaries to YAML since they're all coerced to the same type. The way it's currently done is fully intentional. Of course it doesn't work for everyone, but a single case doesn't convince me that it's wrong.

The constructor `AttributeDict.__init__` is on purpose "dict-like", which is quite complicated, I'm not going to add anything there.

https://docs.python.org/3/library/stdtypes.html#dict

I don't know what you're trying to do, but maybe there's a better way? I wonder if rather than changing the constructor signature, you should use a class method?

```python
class MyAttributeDict(AttributeDict):

    @classmethod
    def from_weird_arguments(cls, ...):
        ...
```

and then do `MyAttributeDict.from_weird_arguments(...)` instead of `MyAttributeDict(...)`

**Comment by ekutner** [comment]
I didn't say the current method was wrong just that it would be useful to be able to choose the desired behavior. 
I assume we can agree that accessing a dictionary using attributes is only relevant when the structure of the dictionary is well known in advance, so it can be referenced directly in code. In my experience, the most common use case for that is for configuration objects, which makes them easy to serialize and deserialize and makes code very clean and elegant. I'm sure there are other use cases which I haven't used. In the few cases where I tried to use AttrDict as a configuration object I always needed additional functions to do stuff at the top level, but never wanted them on children. It's certainly possible to work around the issue by using class methods and default constructors, while also ignoring the fact that irrelevant functions show up when accessing sub-dictionaries, however, it is not elegant in anyway and, at the end of the day, the only reason to use AttrDict in the first is for a more elegant code.

**Comment by otsaloma** [comment]
attd is not a package specifically for configuration. I suspect you might want to make the AttributeDict an instance attribute of a regular class instead, maybe optionally delegate calls so that it'll behave like a dict. Or some other way, but I don't see any reason this configuration-specific consern belongs in a general dict package.

```python
class Configuration:

    def __init__(self, ...):
        self._data = attd.AttributeDict()

    def __getattr__(self, name):
        return getattr(self._data, name)
```

This doesn't sound like a common use pattern. Subclasses are supported, adding options is not an improvement.

https://ometer.com/preferences.html
